// Podcast carousel deck generator.
//
//   POST /api/carousel/preview   { transcript, showName, hostName, presetKey,
//                                  episodeTitle?, episodeNumber? }
//     → { deck: { slides, asset_requests }, usage }
//
// Synchronous (we just await Claude). Used by the /carousel-preview
// page for now; the production flow will move this to a fire-and-
// forget job once we wire it into SocialsSection.
import { Router } from 'express'
import { pool } from '../db'
import { requireUser, type SessionUser } from '../auth'
import { assertWriter } from '../permissions'
import { hasAnthropicKey, generateCarouselDeck, deriveCarouselPreset } from '../anthropic'
import { loadShowStrategyDocs } from './socials'
import { logError, logInfo } from '../diag'

export const carouselRouter = Router()
carouselRouter.use(requireUser)

const MAX_TRANSCRIPT_CHARS = 200_000

carouselRouter.post('/preview', async (req, res) => {
  const user = (req as typeof req & { user: SessionUser }).user
  // Any logged-in user can generate. Each call burns Claude tokens,
  // so we log who's calling and how big the transcript was — that's
  // enough to spot abuse without locking out Caroline / the social team.
  if (!hasAnthropicKey()) {
    res.status(503).json({ error: 'anthropic_key_missing' })
    return
  }
  const {
    transcript, showName, hostName, presetKey,
    episodeTitle, episodeNumber, projectId,
  } = (req.body ?? {}) as Record<string, unknown>

  if (typeof transcript !== 'string' || transcript.trim().length === 0) {
    res.status(400).json({ error: 'transcript_required' })
    return
  }
  if (typeof showName !== 'string' || !showName.trim()) {
    res.status(400).json({ error: 'showName_required' })
    return
  }
  if (typeof presetKey !== 'string' || !presetKey.trim()) {
    res.status(400).json({ error: 'presetKey_required' })
    return
  }
  if (transcript.length > MAX_TRANSCRIPT_CHARS) {
    res.status(400).json({
      error: 'transcript_too_long',
      maxChars: MAX_TRANSCRIPT_CHARS,
      gotChars: transcript.length,
    })
    return
  }

  try {
    // If the caller passed a projectId, verify they can access that
    // project BEFORE we load its strategy docs — otherwise any logged-in
    // user could pass a projectId they don't belong to and have that
    // project's brand positioning baked into a deck. If access is
    // denied, ignore the projectId silently and generate from the
    // transcript alone (deck still returns, just without strategy
    // context).
    let strategyDocs
    if (typeof projectId === 'string' && projectId.trim()) {
      const projRes = await pool.query(
        `SELECT 1 FROM projects p
           LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
          WHERE p.id = $2 AND ($3 = 'admin' OR p.created_by = $1 OR m.user_id IS NOT NULL)
          LIMIT 1`,
        [user.id, projectId.trim(), user.role],
      )
      if (projRes.rows.length > 0) {
        strategyDocs = await loadShowStrategyDocs(projectId.trim())
      }
    }
    const result = await generateCarouselDeck({
      showName: showName.trim(),
      hostName: typeof hostName === 'string' && hostName.trim() ? hostName.trim() : undefined,
      presetKey: presetKey.trim(),
      episodeTitle: typeof episodeTitle === 'string' && episodeTitle.trim() ? episodeTitle.trim() : null,
      episodeNumber: typeof episodeNumber === 'number' ? episodeNumber : null,
      episodeTranscript: transcript,
      strategyDocs,
    })
    // Audit trail so we know who's burning tokens.
    // eslint-disable-next-line no-console
    console.log(
      `[carousel] generated · user=${user.id} show=${showName} chars=${transcript.length} ` +
      `slides=${result.deck.slides.length} input_tokens=${result.usage.inputTokens} ` +
      `output_tokens=${result.usage.outputTokens}`,
    )
    res.json(result)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    logError('carousel route: generation failed', { error: msg, transcriptChars: transcript.length })
    // Surface the actual reason so the UI can show "claude returned no
    // text block" / "invalid JSON" / "anthropic 400 ..." instead of an
    // opaque "generation_failed". Truncate so we never leak a 50KB
    // stack trace into the JSON response.
    res.status(500).json({ error: 'generation_failed', detail: msg.slice(0, 600) })
  }
})

// ─────────────────────────────────────────────────────────────────────
// Persistent per-episode decks (auto-generated by the autopipeline)
// ─────────────────────────────────────────────────────────────────────

// Cached-or-derive a show's preset, server-side (no HTTP round trip).
// Returns null when the show has no cover art or derivation fails —
// callers record why instead of silently skipping.
async function ensureCarouselPreset(projectId: string): Promise<
  { key: string; displayName: string; logo: unknown; palette: unknown } | null
> {
  const { rows } = await pool.query<{
    name: string; slug: string | null; cover_art_url: string | null; carousel_preset: unknown
  }>(
    `SELECT name, slug, cover_art_url, carousel_preset FROM projects WHERE id = $1`,
    [projectId],
  )
  const proj = rows[0]
  if (!proj) return null
  if (proj.carousel_preset) return proj.carousel_preset as { key: string; displayName: string; logo: unknown; palette: unknown }
  if (!proj.cover_art_url || !hasAnthropicKey()) return null
  try {
    const imgRes = await fetch(proj.cover_art_url)
    if (!imgRes.ok) return null
    const ct = (imgRes.headers.get('content-type') || '').toLowerCase()
    const mediaType = ct.includes('png') ? 'image/png' as const
      : ct.includes('webp') ? 'image/webp' as const
      : 'image/jpeg' as const
    const bytes = Buffer.from(await imgRes.arrayBuffer())
    if (bytes.length > 6_000_000) return null
    const derived = await deriveCarouselPreset(bytes, mediaType, proj.name)
    if (!derived) return null
    const preset = {
      key: proj.slug || projectId,
      displayName: proj.name,
      logo: derived.logo,
      palette: derived.palette,
    }
    await pool.query(`UPDATE projects SET carousel_preset = $1 WHERE id = $2`, [JSON.stringify(preset), projectId])
    return preset
  } catch (err) {
    logError('carousel: ensure preset failed', { projectId, error: err instanceof Error ? err.message : String(err) })
    return null
  }
}

function fmtTimecode(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '00:00:00'
  const s = Math.floor(seconds)
  const h = Math.floor(s / 3600)
  const m = Math.floor((s % 3600) / 60)
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`
}

// Generate the episode's deck and persist it. Called by the
// upload-and-go autopipeline after the transcript lands, and by the
// manual (re)generate endpoint. Upserts the one-row-per-episode deck.
export async function generateAndSaveCarouselDeck(args: {
  songId: string
  createdBy?: string | null
}): Promise<void> {
  const sRes = await pool.query<{
    project_id: string; song_title: string; project_name: string; kind: string
  }>(
    `SELECT s.project_id, s.title AS song_title, p.name AS project_name, p.kind
       FROM songs s JOIN projects p ON p.id = s.project_id
      WHERE s.id = $1`,
    [args.songId],
  )
  if (sRes.rows.length === 0) return
  const ctx = sRes.rows[0]
  if (ctx.kind !== 'podcast') return

  async function saveFailed(reason: string, transcriptId?: string | null) {
    await pool.query(
      `INSERT INTO carousel_decks (project_id, song_id, transcript_id, status, error, created_by)
       VALUES ($1, $2, $3, 'failed', $4, $5)
       ON CONFLICT (song_id) DO UPDATE SET
         status = 'failed', error = EXCLUDED.error, updated_at = now()`,
      [ctx.project_id, args.songId, transcriptId ?? null, reason, args.createdBy ?? null],
    )
  }

  if (!hasAnthropicKey()) { await saveFailed('anthropic_key_missing'); return }

  const preset = await ensureCarouselPreset(ctx.project_id)
  if (!preset) { await saveFailed('no_preset_add_cover_art'); return }

  const tRes = await pool.query<{
    id: string
    edited_blocks: Array<{ speaker: string; text: string; start: number; end: number }> | null
  }>(
    `SELECT id, edited_blocks FROM transcripts
      WHERE song_id = $1 AND status = 'done'
      ORDER BY created_at DESC LIMIT 1`,
    [args.songId],
  )
  if (tRes.rows.length === 0) { await saveFailed('no_done_transcript'); return }
  const transcript = tRes.rows[0]
  const transcriptText = (transcript.edited_blocks ?? [])
    .map((b) => `[${fmtTimecode(b.start)}] ${b.speaker}: ${b.text}`)
    .join('\n\n')
    .slice(0, MAX_TRANSCRIPT_CHARS)
  if (transcriptText.length < 100) { await saveFailed('transcript_too_short', transcript.id); return }

  await pool.query(
    `INSERT INTO carousel_decks (project_id, song_id, transcript_id, status, created_by)
     VALUES ($1, $2, $3, 'generating', $4)
     ON CONFLICT (song_id) DO UPDATE SET
       status = 'generating', error = NULL, transcript_id = EXCLUDED.transcript_id, updated_at = now()`,
    [ctx.project_id, args.songId, transcript.id, args.createdBy ?? null],
  )

  try {
    const strategyDocs = await loadShowStrategyDocs(ctx.project_id)
    const result = await generateCarouselDeck({
      showName: ctx.project_name,
      presetKey: preset.key,
      episodeTitle: ctx.song_title,
      episodeTranscript: transcriptText,
      strategyDocs,
    })
    await pool.query(
      `UPDATE carousel_decks
          SET deck = $2::jsonb, status = 'generated', error = NULL,
              input_tokens = $3, output_tokens = $4, updated_at = now()
        WHERE song_id = $1`,
      [args.songId, JSON.stringify(result.deck), result.usage.inputTokens, result.usage.outputTokens],
    )
    logInfo('carousel: episode deck saved', {
      songId: args.songId, slides: result.deck.slides.length,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    logError('carousel: episode deck failed', { songId: args.songId, error: msg })
    await saveFailed(msg.slice(0, 600), transcript.id)
  }
}

// GET the saved deck (+ the show preset the client renders it with).
carouselRouter.get('/decks/:songId', async (req, res) => {
  const user = (req as typeof req & { user: SessionUser }).user
  const songId = req.params.songId
  const access = await pool.query(
    `SELECT s.project_id, p.carousel_preset FROM songs s
       JOIN projects p ON p.id = s.project_id
       LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
      WHERE s.id = $2 AND ($3 = 'admin' OR p.created_by = $1 OR m.user_id IS NOT NULL)
      LIMIT 1`,
    [user.id, songId, user.role],
  )
  if (access.rows.length === 0) { res.status(403).json({ error: 'forbidden' }); return }
  const { rows } = await pool.query(
    `SELECT id, status, error, deck, input_tokens, output_tokens, created_at, updated_at
       FROM carousel_decks WHERE song_id = $1`,
    [songId],
  )
  res.json({ deck: rows[0] ?? null, preset: access.rows[0].carousel_preset ?? null })
})

// (Re)generate the deck for an episode — fire-and-forget; poll the GET.
carouselRouter.post('/decks/:songId/generate', async (req, res) => {
  const user = (req as typeof req & { user: SessionUser }).user
  const songId = req.params.songId
  const sRes = await pool.query<{ project_id: string }>(
    `SELECT project_id FROM songs WHERE id = $1`, [songId],
  )
  if (sRes.rows.length === 0) { res.status(404).json({ error: 'not_found' }); return }
  if (!(await assertWriter(user, sRes.rows[0].project_id, res))) return
  if (!hasAnthropicKey()) { res.status(503).json({ error: 'anthropic_key_missing' }); return }
  void generateAndSaveCarouselDeck({ songId, createdBy: user.id }).catch((err) => {
    logError('carousel: manual generate failed', { songId, error: err instanceof Error ? err.message : String(err) })
  })
  res.json({ ok: true, status: 'generating' })
})

// Auto-derive (and cache) a show's carousel design from its cover art. The
// look is modeled on the show's own art — palette + two-line wordmark — so
// every show's deck is on-brand without a hand-built preset. ?refresh=1
// forces re-derivation (e.g. after the cover art changes).
carouselRouter.get('/preset/:projectId', async (req, res) => {
  const user = (req as typeof req & { user: SessionUser }).user
  const projectId = req.params.projectId
  const refresh = req.query.refresh === '1' || req.query.refresh === 'true'
  const { rows } = await pool.query<{ name: string; slug: string | null; cover_art_url: string | null; carousel_preset: unknown }>(
    `SELECT p.name, p.slug, p.cover_art_url, p.carousel_preset
       FROM projects p
       LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
      WHERE p.id = $2 AND ($3 = 'admin' OR p.created_by = $1 OR m.user_id IS NOT NULL)
      LIMIT 1`,
    [user.id, projectId, user.role],
  )
  const proj = rows[0]
  if (!proj) { res.status(404).json({ error: 'not_found' }); return }
  if (proj.carousel_preset && !refresh) {
    res.json({ preset: proj.carousel_preset, source: 'cached' })
    return
  }
  if (!proj.cover_art_url) {
    res.json({ preset: null, reason: 'no_cover_art' })
    return
  }
  if (!hasAnthropicKey()) { res.status(503).json({ error: 'anthropic_key_missing' }); return }
  try {
    const imgRes = await fetch(proj.cover_art_url)
    if (!imgRes.ok) { res.status(502).json({ error: 'cover_fetch_failed', status: imgRes.status }); return }
    const ct = (imgRes.headers.get('content-type') || '').toLowerCase()
    const mediaType = ct.includes('png') ? 'image/png' as const
      : ct.includes('webp') ? 'image/webp' as const
      : 'image/jpeg' as const
    const bytes = Buffer.from(await imgRes.arrayBuffer())
    if (bytes.length > 6_000_000) { res.status(400).json({ error: 'cover_too_large' }); return }
    const derived = await deriveCarouselPreset(bytes, mediaType, proj.name)
    if (!derived) { res.json({ preset: null, reason: 'derive_failed' }); return }
    const preset = {
      key: proj.slug || projectId,
      displayName: proj.name,
      logo: derived.logo,
      palette: derived.palette,
    }
    await pool.query(`UPDATE projects SET carousel_preset = $1 WHERE id = $2`, [JSON.stringify(preset), projectId])
    res.json({ preset, source: 'derived' })
  } catch (err) {
    logError('carousel: derive preset failed', { projectId, error: err instanceof Error ? err.message : String(err) })
    res.status(500).json({ error: 'derive_failed', detail: err instanceof Error ? err.message.slice(0, 300) : String(err) })
  }
})
