// StudioBinder-style budget template. Used to seed a fresh budget when a
// project enables it. Account codes (10-00 etc.) are industry standard.

export type SeedAccount = {
  code: string
  name: string
  category: 'above_line' | 'production' | 'post' | 'other'
  lineItems?: Array<{ code: string; description: string }>
}

export const STUDIOBINDER_ACCOUNTS: SeedAccount[] = [
  // Above the Line
  {
    code: '10-00',
    name: 'DEVELOPMENT COSTS',
    category: 'above_line',
    lineItems: [
      { code: '10-01', description: 'Prelim Breakdown' },
      { code: '10-02', description: 'Office Expenses' },
      { code: '10-03', description: 'Survey/Scouting' },
      { code: '10-04', description: 'Travel Expenses' },
      { code: '10-05', description: 'Legal' },
      { code: '10-06', description: 'All in' },
    ],
  },
  {
    code: '11-00',
    name: 'STORY & RIGHTS',
    category: 'above_line',
    lineItems: [
      { code: '11-01', description: 'Writers' },
      { code: '11-02', description: 'Script Purchase' },
      { code: '11-03', description: 'Script Copies' },
      { code: '11-04', description: 'Script Timing' },
      { code: '11-05', description: 'Script Clearance Report' },
    ],
  },
  {
    code: '12-00',
    name: 'PRODUCERS UNIT',
    category: 'above_line',
    lineItems: [
      { code: '12-01', description: 'Producer' },
      { code: '12-02', description: 'Co-Producer' },
      { code: '12-03', description: 'Asst to Producers' },
      { code: '12-04', description: 'Producers Entertainment' },
      { code: '12-05', description: 'All In' },
    ],
  },
  {
    code: '13-00',
    name: 'DIRECTOR & STAFF',
    category: 'above_line',
    lineItems: [
      { code: '13-01', description: 'Director' },
      { code: '13-02', description: 'Asst to Director' },
      { code: '13-03', description: 'Director Entertainment' },
      { code: '13-04', description: 'Storyboard Artist' },
      { code: '13-05', description: 'Choreographer' },
      { code: '13-06', description: 'Technical Advisor' },
    ],
  },
  {
    code: '14-00',
    name: 'CAST',
    category: 'above_line',
    lineItems: [
      { code: '14-01', description: 'Lead Cast' },
      { code: '14-02', description: 'Supporting Cast' },
      { code: '14-03', description: 'Day Players' },
      { code: '14-04', description: 'Stunt Coordinators' },
      { code: '14-05', description: 'Stunts & Adjustments' },
      { code: '14-06', description: 'Stunt Equipment' },
      { code: '14-07', description: 'Casting Director' },
      { code: '14-08', description: 'Casting Asst' },
      { code: '14-09', description: 'Casting Expenses' },
      { code: '14-10', description: 'Rehearsal Expenses' },
      { code: '14-11', description: 'Looping / ADR' },
      { code: '14-12', description: 'Mileage' },
      { code: '14-13', description: 'Cast Drivers' },
      { code: '14-14', description: 'Cast Payroll Handling Fees' },
    ],
  },
  {
    code: '15-00',
    name: 'TRAVEL & LIVING',
    category: 'above_line',
    lineItems: [
      { code: '15-01', description: 'Airfares' },
      { code: '15-02', description: 'Transportation' },
      { code: '15-03', description: 'Hotel / Lodging' },
      { code: '15-04', description: 'Per Diem' },
      { code: '15-05', description: 'Self Drive Vehicles & Gas' },
    ],
  },
  // Production
  {
    code: '20-00',
    name: 'PRODUCTION STAFF',
    category: 'production',
    lineItems: [
      { code: '20-01', description: 'Unit Production Manager' },
      { code: '20-02', description: 'Production Coordinator' },
      { code: '20-03', description: '1st Asst Director' },
      { code: '20-04', description: '2nd Asst Director' },
      { code: '20-05', description: 'Script Supervisor' },
      { code: '20-06', description: 'Production Asst (Set)' },
      { code: '20-07', description: 'Production Asst (Office)' },
    ],
  },
  {
    code: '21-00',
    name: 'EXTRA TALENT',
    category: 'production',
    lineItems: [
      { code: '21-01', description: 'Background Extras' },
      { code: '21-02', description: 'Stand-Ins' },
      { code: '21-03', description: 'Extras Casting' },
      { code: '21-04', description: 'Extras Mileage' },
    ],
  },
  {
    code: '22-00',
    name: 'SET DESIGN',
    category: 'production',
    lineItems: [
      { code: '22-01', description: 'Production Designer' },
      { code: '22-02', description: 'Art Director' },
      { code: '22-03', description: 'Asst Art Director' },
      { code: '22-04', description: 'Set Designer' },
      { code: '22-05', description: 'Researcher' },
    ],
  },
  {
    code: '23-00',
    name: 'SET CONSTRUCTION',
    category: 'production',
    lineItems: [
      { code: '23-01', description: 'Construction Coordinator' },
      { code: '23-02', description: 'Construction Foreman' },
      { code: '23-03', description: 'Construction Labor' },
      { code: '23-04', description: 'Painters' },
      { code: '23-05', description: 'Lumber & Hardware' },
      { code: '23-06', description: 'Paint & Supplies' },
      { code: '23-07', description: 'Disposal' },
    ],
  },
  {
    code: '24-00',
    name: 'SET PRE-RIG & STRIKE',
    category: 'production',
    lineItems: [
      { code: '24-01', description: 'Pre-rig Labor' },
      { code: '24-02', description: 'Strike Labor' },
      { code: '24-03', description: 'Pre-rig Equipment' },
    ],
  },
  {
    code: '25-00',
    name: 'SET OPERATIONS',
    category: 'production',
    lineItems: [
      { code: '25-01', description: 'Key Grip' },
      { code: '25-02', description: 'Best Boy Grip' },
      { code: '25-03', description: 'Dolly Grip' },
      { code: '25-04', description: 'Grip(s)' },
      { code: '25-05', description: 'Grip Package Rental' },
      { code: '25-06', description: 'Grip Expendables' },
      { code: '25-07', description: 'Grip Truck' },
    ],
  },
  {
    code: '26-00',
    name: 'SET DRESSING',
    category: 'production',
    lineItems: [
      { code: '26-01', description: 'Set Decorator' },
      { code: '26-02', description: 'Lead' },
      { code: '26-03', description: 'On-Set Dresser' },
      { code: '26-04', description: 'Swing Gang' },
      { code: '26-05', description: 'Set Dressing Rentals' },
      { code: '26-06', description: 'Set Dressing Purchases' },
    ],
  },
  {
    code: '27-00',
    name: 'PROPERTY',
    category: 'production',
    lineItems: [
      { code: '27-01', description: 'Property Master' },
      { code: '27-02', description: 'Asst Props' },
      { code: '27-03', description: 'Prop Rentals' },
      { code: '27-04', description: 'Prop Purchases' },
      { code: '27-05', description: 'Prop Box Rental' },
    ],
  },
  {
    code: '28-00',
    name: 'WARDROBE',
    category: 'production',
    lineItems: [
      { code: '28-01', description: 'Costume Designer' },
      { code: '28-02', description: 'Asst Costume Designer' },
      { code: '28-03', description: 'Wardrobe Supervisor' },
      { code: '28-04', description: 'Set Costumer' },
      { code: '28-05', description: 'Costume Rentals' },
      { code: '28-06', description: 'Costume Purchases' },
      { code: '28-07', description: 'Cleaning' },
    ],
  },
  {
    code: '29-00',
    name: 'ELECTRIC',
    category: 'production',
    lineItems: [
      { code: '29-01', description: 'Gaffer' },
      { code: '29-02', description: 'Best Boy Electric' },
      { code: '29-03', description: 'Electric(s)' },
      { code: '29-04', description: 'Lighting Package Rental' },
      { code: '29-05', description: 'Electric Expendables' },
      { code: '29-06', description: 'Generator' },
      { code: '29-07', description: 'Generator Operator' },
    ],
  },
  {
    code: '30-00',
    name: 'CAMERA',
    category: 'production',
    lineItems: [
      { code: '30-01', description: 'Director of Photography' },
      { code: '30-02', description: 'Camera Operator' },
      { code: '30-03', description: '1st Asst Camera' },
      { code: '30-04', description: '2nd Asst Camera' },
      { code: '30-05', description: 'DIT / Loader' },
      { code: '30-06', description: 'Camera Package Rental' },
      { code: '30-07', description: 'Camera Accessories' },
      { code: '30-08', description: 'Expendables' },
    ],
  },
  {
    code: '31-00',
    name: 'PRODUCTION SOUND',
    category: 'production',
    lineItems: [
      { code: '31-01', description: 'Sound Mixer' },
      { code: '31-02', description: 'Boom Operator' },
      { code: '31-03', description: 'Sound Utility' },
      { code: '31-04', description: 'Sound Package Rental' },
      { code: '31-05', description: 'Wireless Mics' },
      { code: '31-06', description: 'Comtek / IFB' },
    ],
  },
  {
    code: '32-00',
    name: 'MAKE-UP & HAIR',
    category: 'production',
    lineItems: [
      { code: '32-01', description: 'Key Make-Up' },
      { code: '32-02', description: 'Asst Make-Up' },
      { code: '32-03', description: 'Key Hair' },
      { code: '32-04', description: 'Asst Hair' },
      { code: '32-05', description: 'Make-Up Supplies' },
      { code: '32-06', description: 'Hair Supplies' },
    ],
  },
  {
    code: '33-00',
    name: 'TRANSPORTATION',
    category: 'production',
    lineItems: [
      { code: '33-01', description: 'Transportation Coordinator' },
      { code: '33-02', description: 'Transportation Captain' },
      { code: '33-03', description: 'Drivers' },
      { code: '33-04', description: 'Vehicle Rentals' },
      { code: '33-05', description: 'Fuel' },
    ],
  },
  {
    code: '34-00',
    name: 'LOCATIONS',
    category: 'production',
    lineItems: [
      { code: '34-01', description: 'Location Manager' },
      { code: '34-02', description: 'Asst Location Manager' },
      { code: '34-03', description: 'Location Scout' },
      { code: '34-04', description: 'Location Fees' },
      { code: '34-05', description: 'Permits' },
      { code: '34-06', description: 'Site Rep' },
      { code: '34-07', description: 'Parking' },
      { code: '34-08', description: 'Security' },
    ],
  },
  {
    code: '35-00',
    name: 'PICTURE VEHICLES & ANIMALS',
    category: 'production',
    lineItems: [
      { code: '35-01', description: 'Picture Vehicles' },
      { code: '35-02', description: 'Vehicle Wrangler' },
      { code: '35-03', description: 'Animals' },
      { code: '35-04', description: 'Animal Wrangler' },
    ],
  },
  {
    code: '36-00',
    name: 'SPECIAL EFFECTS',
    category: 'production',
    lineItems: [
      { code: '36-01', description: 'SFX Coordinator' },
      { code: '36-02', description: 'SFX Foreman' },
      { code: '36-03', description: 'SFX Tech' },
      { code: '36-04', description: 'SFX Equipment' },
      { code: '36-05', description: 'SFX Materials' },
    ],
  },
  {
    code: '37-00',
    name: 'VISUAL EFFECTS - PRODUCTION',
    category: 'production',
    lineItems: [
      { code: '37-01', description: 'VFX Supervisor (Set)' },
      { code: '37-02', description: 'VFX Plates / Witness Cam' },
      { code: '37-03', description: 'On-Set Markers / Tracking' },
    ],
  },
  {
    code: '38-00',
    name: 'FILM & LAB',
    category: 'production',
    lineItems: [
      { code: '38-01', description: 'Film Stock' },
      { code: '38-02', description: 'Processing' },
      { code: '38-03', description: 'Dailies' },
      { code: '38-04', description: 'Hard Drives / Media' },
      { code: '38-05', description: 'DIT Cart' },
    ],
  },
  {
    code: '39-00',
    name: 'BTL TRAVEL & LIVING',
    category: 'production',
    lineItems: [
      { code: '39-01', description: 'Crew Airfares' },
      { code: '39-02', description: 'Crew Hotels' },
      { code: '39-03', description: 'Crew Per Diem' },
      { code: '39-04', description: 'Mileage' },
      { code: '39-05', description: 'Self-Drive Vehicles & Gas' },
    ],
  },
  // Post
  {
    code: '45-00',
    name: 'FILM EDITING',
    category: 'post',
    lineItems: [
      { code: '45-01', description: 'Editor' },
      { code: '45-02', description: 'Asst Editor' },
      { code: '45-03', description: 'Edit Suite Rental' },
      { code: '45-04', description: 'Edit Hardware / Software' },
      { code: '45-05', description: 'Picture Conform' },
    ],
  },
  {
    code: '46-00',
    name: 'MUSIC',
    category: 'post',
    lineItems: [
      { code: '46-01', description: 'Composer' },
      { code: '46-02', description: 'Music Editor' },
      { code: '46-03', description: 'Music Licensing' },
      { code: '46-04', description: 'Score Recording' },
      { code: '46-05', description: 'Music Clearance' },
    ],
  },
  {
    code: '47-00',
    name: 'VISUAL EFFECTS',
    category: 'post',
    lineItems: [
      { code: '47-01', description: 'VFX Supervisor' },
      { code: '47-02', description: 'VFX Artists' },
      { code: '47-03', description: 'VFX Shots' },
      { code: '47-04', description: 'VFX Software / Render' },
    ],
  },
  {
    code: '48-00',
    name: 'POST PRODUCTION SOUND',
    category: 'post',
    lineItems: [
      { code: '48-01', description: 'Sound Designer' },
      { code: '48-02', description: 'Re-Recording Mixer' },
      { code: '48-03', description: 'Foley Artist' },
      { code: '48-04', description: 'ADR Recording' },
      { code: '48-05', description: 'Sound Effects Library' },
      { code: '48-06', description: 'Mix Stage Rental' },
    ],
  },
  {
    code: '49-00',
    name: 'POST PRODUCTION FILM & LAB',
    category: 'post',
    lineItems: [
      { code: '49-01', description: 'Color Correction' },
      { code: '49-02', description: 'Colorist' },
      { code: '49-03', description: 'DI Suite' },
      { code: '49-04', description: 'Deliverables / Masters' },
      { code: '49-05', description: 'Closed Captioning' },
    ],
  },
  // Other
  {
    code: '55-00',
    name: 'PUBLICITY',
    category: 'other',
    lineItems: [
      { code: '55-01', description: 'Unit Publicist' },
      { code: '55-02', description: 'EPK Crew' },
      { code: '55-03', description: 'Stills Photographer' },
      { code: '55-04', description: 'Press Materials' },
      { code: '55-05', description: 'Premiere' },
    ],
  },
  {
    code: '56-00',
    name: 'LEGAL & ACCOUNTING',
    category: 'other',
    lineItems: [
      { code: '56-01', description: 'Legal Fees' },
      { code: '56-02', description: 'Production Accountant' },
      { code: '56-03', description: 'Asst Accountant' },
      { code: '56-04', description: 'Payroll Service' },
      { code: '56-05', description: 'Tax Prep' },
    ],
  },
  {
    code: '57-00',
    name: 'GENERAL EXPENSE',
    category: 'other',
    lineItems: [
      { code: '57-01', description: 'Office Rent' },
      { code: '57-02', description: 'Office Supplies' },
      { code: '57-03', description: 'Phone & Internet' },
      { code: '57-04', description: 'Copying' },
      { code: '57-05', description: 'Postage / Shipping' },
      { code: '57-06', description: 'Petty Cash' },
    ],
  },
  {
    code: '58-00',
    name: 'INSURANCE',
    category: 'other',
    lineItems: [
      { code: '58-01', description: 'Production Package' },
      { code: '58-02', description: 'E&O Insurance' },
      { code: '58-03', description: 'Workers Comp' },
      { code: '58-04', description: 'Auto Insurance' },
    ],
  },
]

export const CATEGORY_LABEL: Record<SeedAccount['category'], string> = {
  above_line: 'Above the Line',
  production: 'Production',
  post: 'Post-Production',
  other: 'Other',
}

export const CATEGORY_ORDER: Array<SeedAccount['category']> = [
  'above_line',
  'production',
  'post',
  'other',
]
