-- Per-day social content plans for podcast episodes. Each row holds one
-- plan generated by Claude for one (project, song, transcript) tuple,
-- plus per-item status and edits so the team can track plan → posted.
--
-- Per-show brand voice + example posts live on projects so they're
-- reused across every episode of that show.
ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS socials_brand_voice text,
  ADD COLUMN IF NOT EXISTS socials_example_posts jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS social_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  song_id uuid NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  transcript_id uuid REFERENCES transcripts(id) ON DELETE SET NULL,
  -- Each item is one of:
  --   { id, kind: "text_post",   status, text, ai_text }
  --   { id, kind: "story_text",  status, text, ai_text }
  --   { id, kind: "reel_concept",  status, hook, talking_points, suggested_clip }
  --   { id, kind: "photo_concept", status, image_direction, caption, vibe }
  -- status: idea | drafted | scheduled | posted
  -- text / ai_text on text+story items: user-edited copy + the original AI
  -- copy so we can re-render or restore.
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'generating'
    CHECK (status IN ('generating', 'generated', 'failed')),
  error text,
  -- For cost tracking
  input_tokens integer,
  output_tokens integer,
  cache_read_tokens integer,
  cache_create_tokens integer,
  created_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_social_plans_song ON social_plans(song_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_plans_project ON social_plans(project_id, created_at DESC);
